setwd("~/Documents/Personal/Coursera/Exploratory Data Analysis/ExData_Plotting1")
household_power_consumption <- read.csv("~/Documents/Personal/Coursera/Exploratory Data Analysis/household_power_consumption.txt", sep=";")
attach(household_power_consumption)
project1 <- subset(household_power_consumption,Date %in% c('1/2/2007','2/2/2007') )
y<-strptime(paste(project1[,"Date"],project1[,"Time"]),"%d/%m/%Y%H:%M:%S")
z<-as.numeric(as.character(project1[,"Global_active_power"]))
plot(y,z,type="l",xlab="",ylab="Global Active Power (kilowatts)")
dev.print(png,file="plot2.png",width=480,height=480)
dev.off()
