setwd("~/Documents/Personal/Coursera/Exploratory Data Analysis/ExData_Plotting1")
household_power_consumption <- read.csv("~/Documents/Personal/Coursera/Exploratory Data Analysis/household_power_consumption.txt", sep=";")
attach(household_power_consumption)
project1 <- subset(household_power_consumption,Date %in% c('1/2/2007','2/2/2007') )
y<-strptime(paste(project1[,"Date"],project1[,"Time"]),"%d/%m/%Y%H:%M:%S")
z<-as.numeric(as.character(project1[,"Global_active_power"]))
png(filename="plot4.png", width=480, height=480)
par(mfcol=c(2,2))
plot(y,z,type="l",xlab="",ylab="Global Active Power")
z1<-as.numeric(as.character(project1[,"Sub_metering_1"]))
z2<-as.numeric(as.character(project1[,"Sub_metering_2"]))
z3<-as.numeric(as.character(project1[,"Sub_metering_3"]))
plot(y,z1,type="l",xlab="",ylab="Energy sub metering")
lines(y,z2,type="l",xlab="",ylab="",col="red")
lines(y,z3,type="l",xlab="",ylab="",col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=1,col=c("black","red","blue"),bty="n")
voltage<-as.numeric(as.character(project1[,"Voltage"]))
plot(y,voltage,type="l",xlab="datetime",ylab="Voltage")
a<-as.numeric(as.character(project1[,"Global_reactive_power"]))
plot(y,a,type="l",xlab="datetime",ylab="Global_reactive_power")
dev.off()
