setwd("~/Documents/Personal/Coursera/Exploratory Data Analysis/ExData_Plotting1")
household_power_consumption <- read.csv("~/Documents/Personal/Coursera/Exploratory Data Analysis/household_power_consumption.txt", sep=";")
attach(household_power_consumption)
as.Date(household_power_consumption[,"Date"],"dd/mm/yyyy")
project1 <- subset(household_power_consumption,Date %in% c('1/2/2007','2/2/2007') )
x<-as.numeric(as.character(project1[,"Global_active_power"]))
hist(x,col="red",xlab="Global Active Power (kilowatts)",ylab="Frequency",main="Global Active Power",xaxt="n")
axis(side=1,at=c(0,2,4,6))
dev.print(png,file="plot1.png",width=480,height=480)
dev.off()
